Repository indrakishore/Developers-Community, pull requests merged in 2024-10, with the labels that each got.

#3 Added 2 Searching Techniques with code and example
  DSA/SearchbyKrit.java
Labels: enhancement, good first issue, Hactoberfest

#5 Create LinkedListImplementaionByAnurag.java
  DSA/LinkedListImplementaionByAnurag.java
Labels: Hactoberfest, hactoberfest-accepted

#7 MoveZerosToEndByAnurag0git.java
  DSA/MoveZerosToEndByAnurag0git.java
Labels: Hactoberfest, hactoberfest-accepted

#8 FindSecondMaximumByAnurag0git.java
  DSA/FindSecondMaximumByAnurag0git.java
Labels: Hactoberfest, hactoberfest-accepted

#10 Stack Implementation
  DSA/StackUsingArrayByShalini.java
  DSA/StackUsingLinkedListByShalini.java
  DSA/StackUsingStackClassByShalini.java
Labels: Hactoberfest, hactoberfest-accepted

#16 BrowserHistoryByAnurag0git.java
  BrowserHistoryByAnurag0git.java
Labels: Hactoberfest, hactoberfest-accepted

#18 Update Pull_Request_Using_Git.md
  Pull_Request_Using_Git.md
Labels: Hactoberfest, hactoberfest-accepted

#19 solved Queue Implementation #12
  DSA/QueueByIshika1880.java
Labels: Hactoberfest, hactoberfest-accepted

#25 To DO app in java project started as mentioned in issue #1
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  ToDoListAppByAnurag0git/.gitignore
  ToDoListAppByAnurag0git/.idea/.gitignore
  ToDoListAppByAnurag0git/app/.gitignore
  ToDoListAppByAnurag0git/app/build.gradle.kts
  ToDoListAppByAnurag0git/app/proguard-rules.pro
  ToDoListAppByAnurag0git/app/src/androidTest/java/com/example/anurag0git/ExampleInstrumentedTest.java
  ToDoListAppByAnurag0git/app/src/main/AndroidManifest.xml
  ToDoListAppByAnurag0git/app/src/main/java/com/example/anurag0git/MainActivity.java
  ToDoListAppByAnurag0git/app/src/main/res/drawable/ic_launcher_background.xml
  ToDoListAppByAnurag0git/app/src/main/res/drawable/ic_launcher_foreground.xml
  ToDoListAppByAnurag0git/app/src/main/res/layout/activity_main.xml
  ToDoListAppByAnurag0git/app/src/main/res/layout/card.xml
  ToDoListAppByAnurag0git/app/src/main/res/layout/dialog.xml
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  ToDoListAppByAnurag0git/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  ToDoListAppByAnurag0git/app/src/main/res/values-night/themes.xml
  ToDoListAppByAnurag0git/app/src/main/res/values/colors.xml
  ToDoListAppByAnurag0git/app/src/main/res/values/strings.xml
  ToDoListAppByAnurag0git/app/src/main/res/values/themes.xml
  ToDoListAppByAnurag0git/app/src/main/res/xml/backup_rules.xml
  ToDoListAppByAnurag0git/app/src/main/res/xml/data_extraction_rules.xml
  ToDoListAppByAnurag0git/app/src/test/java/com/example/anurag0git/ExampleUnitTest.java
  ToDoListAppByAnurag0git/build.gradle.kts
  ToDoListAppByAnurag0git/gradle.properties
  ToDoListAppByAnurag0git/gradle/libs.versions.toml
  ToDoListAppByAnurag0git/gradle/wrapper/gradle-wrapper.jar
  ToDoListAppByAnurag0git/gradle/wrapper/gradle-wrapper.properties
  ToDoListAppByAnurag0git/gradlew
  ToDoListAppByAnurag0git/gradlew.bat
  ToDoListAppByAnurag0git/settings.gradle.kts
Labels: Hactoberfest, hactoberfest-accepted

#27 Revert "Add Design Browser History"
  DSA/DesignBrowserHistoryByManojith.cpp
Labels: Hactoberfest, hactoberfest-accepted

#14 Added a java code for ValidateIndexKValueGreaterThanZero.java
  DSA/ValidateIndexKValueGreaterThanZeroByFarihaNaqvi.java
Labels: Hactoberfest, hactoberfest-accepted

#11 Next Greater Element
  DSA/NGE.java
Labels: Hactoberfest, hactoberfest-accepted

#33 Create BestTimeToSellAndBuyStock.java
  DSA/BestTimeToSellAndBuyStockbyAnuragSingh.java
Labels: Hactoberfest, hactoberfest-accepted

#34 Create FindMiddleElementInLinkedListByAnurag0git.java
  DSA/FindMiddleElementInLinkedListByAnurag0git.java
Labels: Hactoberfest, hactoberfest-accepted

#51 Mansi Bhandari
  BrowserHistory.class
  BrowserHistoryDesignByMansiBhandari.java
  DesignBrowserHistory.class
Labels: Hactoberfest, hactoberfest-accepted, level-1

#64 Added Expense Tracker
  Frontend/ExpenseTrackerByShalini/index.html
  Frontend/ExpenseTrackerByShalini/readme.md
  Frontend/ExpenseTrackerByShalini/script.js
  Frontend/ExpenseTrackerByShalini/style.css
Labels: Hactoberfest, hactoberfest-accepted, gsoc-ext, level-3

#63 Added program of Sutherland-Hodgman algorithm
  Sutherland-Hodgman.cpp
Labels: Hactoberfest, hactoberfest-accepted, level-1

#68 Add BalancedParentheses.java to DSA Folder
  DSA/BalancedParenthesesByVIsheshJain.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#69 Create DijkstraSolutionByKhushi.java
  DSA/DijkstrasAlgorithmByKhushi.java
Labels: Hactoberfest, hactoberfest-accepted, level-1, gsoc-ext

#60 Create TopoLogicalSortByOm.java
  DSA/Graph/TopoLogicalSortByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#79 Buy and sell Stock
  DSA/BuyAndSellBySaloni.cpp
  DSA/BuyAndSellStockBySaloni.cpp
Labels: Hactoberfest, hactoberfest-accepted, level-1

#78 Bookmark functionality added#75
  ToDoListAppByAnurag0git/Bookmark.cpp
  ToDoListAppByAnurag0git/bookmark_function.exe
  ToDoListAppByAnurag0git/output/Bookmark.exe
  ToDoListAppByAnurag0git/output/bookmark_function.exe
  ToDoListAppByAnurag0git/output/boomark.exe
Labels: Hactoberfest, hactoberfest-accepted, level-1

#74 Added new Programs
  DSA/SudokuSolver.java
  DSA/TowerofHanoi.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#59 Create DijkstraAlgorithByOm.java
  DSA/Graph/DijkstraAlgorithByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#80 added 3d rotating card project
  Frontend/3d Rotating Card Project/index.html
  Frontend/3d Rotating Card Project/styles.css
Labels: Hactoberfest, hactoberfest-accepted, level-1

#85 Adding Finding Peak Element Problem code in java in DSA Folder #71
  DSA/BestTimeToBuyAndSellStock.class
  DSA/BestTimeToBuyAndSellStock.java
  DSA/PeakElementFinder.java
  DSA/PeakElementFinderByMahi.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#94 Implemented Java Code for Maximum Depth of Binary Tree
  DSA/BestTimeToBuyAndSellStockByMahi.java
  DSA/MaximumDepthBinaryTreeByMahi.java
  DSA/NextGreaterElement.java
Labels: Hactoberfest, hactoberfest-accepted, gsoc-ext

#43 Palindrome Linked List Solution in Java#42
  DSA/PlaindromeLinkedList.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#39 Create BellManFordAlgoByOm.java
  DSA/Graph/BellManFordAlgoByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#37 KnapsackProblemByOm.java
  DSA/DynamicProblems/KnapsackProblemByOm.java
Labels: Hactoberfest, hactoberfest-accepted

#36 TopoLogicalSortByOm.java
  DSA/TopoLogicalSortByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#35 MiddleElementLinkedlistByOm.java
  DSA/MiddleElementLinkedlistByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#52 Banker'sAlgorithmByPallavi.c
  DSA/Banker'sAlgorithmByPallavi.c
Labels: Hactoberfest, hactoberfest-accepted, level-1

#53 Added Doubly linked list implementation in java
  DSA/Doublylinkedlistimplementationbyatr.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#56 Create QueueImplementationByOm.java
  DSA/Queue/QueueImplementationByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#57 Create KruskalsAlgorithmByOm.java
  DSA/Graph/KruskalsAlgorithmByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#58 Create MaxHeightBTByOm.java
  DSA/BinaryTree/MaxHeightBTByOm.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#67 Create MergekSortedListsByKrishna.java
  DSA/MergekSortedListsByKrishna.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#70 MissingNumberByRiya.java
  DSA/missing_number.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#83 Created HeapSort.java
  DSA/Sorting/HeapSort.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#84 Create Prime.cpp
  Prime.cpp
Labels: Hactoberfest, hactoberfest-accepted, level-1

#104 Book allocation problem using Binary Search
  DSA/BookAllocationProblemBinarySearch.cpp
Labels: Hactoberfest, hactoberfest-accepted, level-1

#103 TCSmock1ByAnurag0git
  DSA/TCS_CodeVita2k24/TCSmock1que1.java
  DSA/TCS_CodeVita2k24/TCSmock1que2.java
  DSA/TCS_CodeVita2k24/TCSmock1que3.java
  DSA/TCS_CodeVita2k24/TCSmock1que4.java
  DSA/TCS_CodeVita2k24/TCSmock1que5.java
  DSA/TCS_CodeVita2k24/TCSmock1que6.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#100 Create FrogJumpByAnkita.cpp
  DSA/FrogJumpByAnkita.cpp
Labels: Hactoberfest, hactoberfest-accepted, level-1

#99 To-Do List App
  ToDoAppSpuskar/Main.java
  ToDoAppSpuskar/Task.java
  ToDoAppSpuskar/TaskManager.java
Labels: Hactoberfest, hactoberfest-accepted

#107 tic-tac-toe game
  android-apps/Connect3Game/.gitignore
  android-apps/Connect3Game/.idea/.gitignore
  android-apps/Connect3Game/.idea/compiler.xml
  android-apps/Connect3Game/.idea/deploymentTargetDropDown.xml
  android-apps/Connect3Game/.idea/deploymentTargetSelector.xml
  android-apps/Connect3Game/.idea/gradle.xml
  android-apps/Connect3Game/.idea/jarRepositories.xml
  android-apps/Connect3Game/.idea/migrations.xml
  android-apps/Connect3Game/.idea/misc.xml
  android-apps/Connect3Game/.idea/runConfigurations.xml
  android-apps/Connect3Game/app/.gitignore
  android-apps/Connect3Game/app/build.gradle
  android-apps/Connect3Game/app/proguard-rules.pro
  android-apps/Connect3Game/app/src/androidTest/java/com/example/connect3game/ExampleInstrumentedTest.java
  android-apps/Connect3Game/app/src/main/AndroidManifest.xml
  android-apps/Connect3Game/app/src/main/java/com/example/connect3game/MainActivity.java
  android-apps/Connect3Game/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android-apps/Connect3Game/app/src/main/res/drawable/board.png
  android-apps/Connect3Game/app/src/main/res/drawable/ic_launcher_background.xml
  android-apps/Connect3Game/app/src/main/res/drawable/red.png
  android-apps/Connect3Game/app/src/main/res/drawable/yellow.png
  android-apps/Connect3Game/app/src/main/res/layout/activity_main.xml
  android-apps/Connect3Game/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android-apps/Connect3Game/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android-apps/Connect3Game/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android-apps/Connect3Game/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android-apps/Connect3Game/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android-apps/Connect3Game/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android-apps/Connect3Game/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android-apps/Connect3Game/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android-apps/Connect3Game/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android-apps/Connect3Game/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android-apps/Connect3Game/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android-apps/Connect3Game/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android-apps/Connect3Game/app/src/main/res/raw/coinsound.mp3
  android-apps/Connect3Game/app/src/main/res/values-night/themes.xml
  android-apps/Connect3Game/app/src/main/res/values/colors.xml
  android-apps/Connect3Game/app/src/main/res/values/strings.xml
  android-apps/Connect3Game/app/src/main/res/values/themes.xml
  android-apps/Connect3Game/app/src/test/java/com/example/connect3game/ExampleUnitTest.java
  android-apps/Connect3Game/build.gradle
  android-apps/Connect3Game/gradle.properties
  android-apps/Connect3Game/gradle/wrapper/gradle-wrapper.jar
  android-apps/Connect3Game/gradle/wrapper/gradle-wrapper.properties
  android-apps/Connect3Game/gradlew
  android-apps/Connect3Game/gradlew.bat
  android-apps/Connect3Game/settings.gradle
Labels: Hactoberfest, hactoberfest-accepted, level-3

#109 merge sort java.
  DSA/Sorting/Bubble._sort.java
  DSA/Sorting/Insertion_sort.java
  DSA/Sorting/Merge_sort.java
  DSA/Sorting/Quick_sort.java
  DSA/Sorting/Selection_sort.java
Labels: Hactoberfest, hactoberfest-accepted, gsoc-ext

#112 added landing page using html and css
  Frontend/Landing Page Using Html and Css/index.html
  Frontend/Landing Page Using Html and Css/styles.css
Labels: Hactoberfest, hactoberfest-accepted, level-1

#113 Added the code of Merge Sort, Selection Sort and Bubble Sort
  DSA/Sorting/BubbleSort.java
  DSA/Sorting/MergeSort.java
  DSA/Sorting/SelectionSort.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#123 bucket sort and counting sort
  DSA/BitManupulation/PowerOf_two.class
  DSA/BitManupulation/PowerOf_two.java
  DSA/BitManupulation/XOR_subset.class
  DSA/BitManupulation/XOR_subset.java
  DSA/Sorting/Bubble._sort.java
  DSA/Sorting/Bucket_sort.java
  DSA/Sorting/Counting_sort.java
  DSA/Sorting/Insertion_sort.java
  DSA/Sorting/Merge_sort.java
  DSA/Sorting/Quick_sort.java
  DSA/Sorting/Radix_sort.java
  DSA/Sorting/SelectionSort.java
  DSA/Sorting/Selection_sort.java
Labels: Hactoberfest, hactoberfest-accepted, level-1, gsoc-ext

#132 Issue : #131 : Added DSA Question findDiameterofBinaryTreebycodeforlifeee.java
  DSA/BinaryTree/findDiameterofBinaryTreebycodeforlifeee.java
Labels: Hactoberfest, hactoberfest-accepted, gsoc-ext

#121 Added the code of Quick Sort and Insertion Sort Algorithms
  DSA/BinaryTree/BinaryTreesB.java
  DSA/BinaryTree/CountNodes.java
  DSA/BinaryTree/Diameter.java
  DSA/BinaryTree/HeightOfTree.java
  DSA/BinaryTree/KthAncestor.java
  DSA/BinaryTree/KthLevel.java
  DSA/BinaryTree/LevelOrderTraversal.java
  DSA/BinaryTree/LowestCommonAncestor.java
  DSA/BinaryTree/MinimumDistance.java
  DSA/BinaryTree/SubTree.java
  DSA/BinaryTree/SumOfNodes.java
  DSA/BinaryTree/TopViewTree.java
  DSA/BinaryTree/TransformSum.java
  DSA/Sorting/Insertionsort.java
  DSA/Sorting/Quicksort.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#118 #93 Linked list header file
  DSA/linkedlist/LinkedListHeaderFile.h
Labels: Hactoberfest, hactoberfest-accepted, level-3

#102 Created 0-1knapsack in java
  DSA/0-1knapsack.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#98 Create BrowserHistory.java
  DSA/BrowserHistory.java
Labels: Hactoberfest, hactoberfest-accepted, level-1

#105 rat in maze prob
  DSA/RatInMaze.cpp
Labels: Hactoberfest, hactoberfest-accepted, level-1, gsoc-ext
